name: Build only

on:
  push:
    branches: [main]
  pull_request:

jobs:
  docker-push:
    name: Build but do not push container image
    runs-on: ubuntu-latest
    environment: docker-builder

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Build image
        uses: docker/build-push-action@v2
        with:
          context: ./
          tags: |
            styraautomation/entitlements-samples:${{ github.ref_name }}
          builder: ${{ steps.buildx.outputs.name }}
          push: false

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
