name: Build and Publish

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  docker-push:
    name: Build and push container image
    runs-on: ubuntu-latest
    environment: docker-builder

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@master
        with:
          platforms: all

      - name: Build image and push to Docker Hub
        uses: docker/build-push-action@v2
        with:
          context: ./
          tags: |
            styra/entitlements-samples:${{ github.ref_name }}
            styra/entitlements-samples:latest
          builder: ${{ steps.buildx.outputs.name }}
          platforms: linux/amd64,linux/arm64
          push: true

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
